version: '3.7'

networks:
  app-tier:
    driver: bridge

services:

  postgresql:
    image: postgres
    hostname: postgresql
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./postgresql/sql_init//:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-tier

  api:
    build:
      context: api
    hostname: api
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      - postgresql
      - minio
    env_file:
      - .env
    networks:
      - app-tier

  worker:
    build:
      context: worker
    hostname: worker
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: worker.2

    depends_on:
      - postgresql
      - api
      - minio
    env_file:
      - .env
    networks:
      - app-tier

  minio:
    image: 'minio/minio'
    hostname: minio
    ports:
      - "9000:9000"
    volumes:
    - minio:/data
    restart: always
    env_file:
      - .env
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-tier

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
    - "24224:24224"
    - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.9.0
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.9.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"


volumes:
  minio:
  database_postgres: