version: '3.7'

services:

  postgresql:
    image: postgres
    hostname: postgresql
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./postgresql/sql_init//:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3


  api:
    build:
      context: api
    hostname: api
    ports:
    - "8080:8080"
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: api.01
    depends_on:
      - postgresql
      - minio
      - fluentd
      - elasticsearch
      - kibana
    env_file:
      - .env


  worker:
    build:
      context: worker
    hostname: worker
    restart: always
    depends_on:
      - postgresql
      - api
      - minio
      - fluentd
      - elasticsearch
      - kibana
    env_file:
      - .env


  minio:
    image: 'minio/minio'
    hostname: minio
    ports:
      - "9000:9000"
    volumes:
    - minio:/data
    restart: always
    env_file:
      - .env
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
    - "24224:24224"
    - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.9.0
    expose:
      - 9200
    ports:
      - "9200:9200"
    environment:
      - "cluster.name=docker-cluster"
      - "network.host=0.0.0.0"
      - "transport.host=0.0.0.0"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"

  kibana:
    image: kibana:7.9.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M


volumes:
  minio:
  database_postgres: